export const FETCH_APPOINTMENTS = 'FETCH_APPOINTMENTS';
export const NEW_APPOINTMENT = 'NEW_APPOINTMENTS';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const EDIT_APPOINTMENT = 'EDIT_APPOINTMENT';

export const NEW_USER = 'NEW_USER';
export const LOGIN_USER = 'LOGIN_USER';